### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by Arthur1967** [OfficerKD637/repository.officerkd637#1]
I'm currently using Arctic Zephyr two resurrection I want to use your skin, but I've tried ,how do I get it to look like this? I've asked everywhere and no one answers. Hopefully you can help[[![image](https://github.com/user-attachments/assets/3352cb65-b1d1-41e5-a1c4-616b4e002c38)]()]() thank you

**Comment by Arthur1967** [comment]
I will Close this for now, but I can't figure it out

**Comment by OfficerKD637** [comment]
Hi!

Sorry for the late reply!

If you set 'Sidemenu > Minimize' to either 'Library', 'Media', or 'Always', you'll find an option called 'Sidemenu > Expand labels from minimized' -- try enabling it and it should help you achieve something similar to your attached image.

**Comment by Arthur1967** [comment]
No worries, my friend. Thank you for the reply. Everybody is busy. I will try that.
